add actions

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -6,15 +6,27 @@ on:
   pull_request:
     branches: [ "main" ]
 
-env:
-  IMAGE_NAME: uofthacks12-backend
-
 jobs:
   build-and-push:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4
     
+    - name: List files in workspace
+      run: ls -la
+      
+    - name: Print directory contents
+      run: ls -R
+      
+    - name: Check for Dockerfile
+      run: |
+        if [ -f "Dockerfile" ]; then
+          echo "Dockerfile found"
+        else
+          echo "Dockerfile not found"
+          exit 1
+        fi
+      
     - name: Login to Docker Hub
       uses: docker/login-action@v3
       with:
@@ -27,4 +39,4 @@ jobs:
         context: .
         file: ./Dockerfile
         push: true
-        tags: codejediondockerhub/${{ env.IMAGE_NAME }}:latest
+        tags: codejediondockerhub/uofthacks12-backend:latest
